package builder;

public class XMLStringBuilder {
	private XMLStringBuilder() {
	};

	public static String get3EntriesFrom2ClassesSameRule1ClassRuleDuplicate() {
		return "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\r\n"
				+ "<pmd "
				+ "xmlns=\"http://pmd.sourceforge.net/report/2.0.0\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" "
				+ "xsi:schemaLocation=\"http://pmd.sourceforge.net/report/2.0.0 http://pmd.sourceforge.net/report_2_0_0.xsd\" "
				+ "version=\"6.29.0\" timestamp=\"2021-02-10T17:16:52.344\">\r\n"
				+ "<file "
				+ "name=\"/home/jpeuker/git/PMD_Report_Extractor/src/main/java/de/PMD_Report_Extractor/App.java\">\n"
				+ "<violation "
				+ "beginline=\"41\" endline=\"42\" begincolumn=\"4\" endcolumn=\"83\" rule=\"GuardLogStatement\" "
				+ "ruleset=\"Best Practices\" package=\"de.PMD_Report_Extractor\" class=\"App\" method=\"main\" "
				+ "externalInfoUrl=\"https://pmd.github.io/pmd-6.29.0/pmd_rules_java_bestpractices.html#guardlogstatement\" "
				+ "priority=\"2\">\nLogger calls should be surrounded by log level guards.\n"
				+ "</violation>\r\n"
				+ "</file>\r\n"
				+ "<file "
				+ "name=\"/home/jpeuker/git/PMD_Report_Extractor/src/main/java/de/PMD_Report_Extractor/util/ResourceFileHandler.java\">\n"
				+ "<violation "
				+ "beginline=\"25\" endline=\"25\" begincolumn=\"4\" endcolumn=\"41\" rule=\"GuardLogStatement\" "
				+ "ruleset=\"Best Practices\" package=\"de.PMD_Report_Extractor.util\" class=\"ResourceFileHandler\" "
				+ "method=\"readFile\" externalInfoUrl=\"https://pmd.github.io/pmd-6.29.0/pmd_rules_java_bestpractices.html"
				+ "#guardlogstatement\" priority=\"2\">\nLogger calls should be surrounded by log level guards.\n"
				+ "</violation>"
				+ "<violation "
				+ "beginline=\"39\" endline=\"39\" begincolumn=\"4\" endcolumn=\"44\" rule=\"GuardLogStatement\" "
				+ "ruleset=\"Best Practices\" package=\"de.PMD_Report_Extractor.util\" class=\"ResourceFileHandler\" "
				+ "method=\"writeToFile\" externalInfoUrl=\"https://pmd.github.io/pmd-6.29.0/pmd_rules_java_bestpractices.html"
				+ "#guardlogstatement\" priority=\"2\">\nLogger calls should be surrounded by log level guards.\n"
				+ "</violation>\r\n"
				+ "</file>\r\n"
				+ "</pmd>";
	}

	public static String get4EntriesFrom2ClassesWith2Rules1ClassRuleDuplicate() {
		return "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\r\n"
				+ "<pmd "
				+ "xmlns=\"http://pmd.sourceforge.net/report/2.0.0\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" "
				+ "xsi:schemaLocation=\"http://pmd.sourceforge.net/report/2.0.0 http://pmd.sourceforge.net/report_2_0_0.xsd\" "
				+ "version=\"6.29.0\" timestamp=\"2021-02-10T17:16:52.344\">\r\n"
				+ "<file "
				+ "name=\"/home/jpeuker/git/PMD_Report_Extractor/src/main/java/de/PMD_Report_Extractor/App.java\">\n"
				+ "<violation "
				+ "beginline=\"19\" endline=\"48\" begincolumn=\"18\" endcolumn=\"1\" rule=\"UseUtilityClass\" "
				+ "ruleset=\"Design\" package=\"de.PMD_Report_Extractor\" class=\"App\" "
				+ "externalInfoUrl=\"https://pmd.github.io/pmd-6.29.0/pmd_rules_java_design.html#useutilityclass\" priority=\"3\">\n"
				+ "All methods are static.  Consider using a utility class instead. Alternatively, you could add a "
				+ "private constructor or make the class abstract to silence this warning.\n"
				+ "</violation>\n"
				+ "<violation "
				+ "beginline=\"41\" endline=\"42\" begincolumn=\"4\" endcolumn=\"83\" rule=\"GuardLogStatement\" "
				+ "ruleset=\"Best Practices\" package=\"de.PMD_Report_Extractor\" class=\"App\" method=\"main\" "
				+ "externalInfoUrl=\"https://pmd.github.io/pmd-6.29.0/pmd_rules_java_bestpractices.html#guardlogstatement\" "
				+ "priority=\"2\">\nLogger calls should be surrounded by log level guards.\n"
				+ "</violation>\r\n"
				+ "</file>\r\n"
				+ "<file "
				+ "name=\"/home/jpeuker/git/PMD_Report_Extractor/src/main/java/de/PMD_Report_Extractor/util/ResourceFileHandler.java\">\n"
				+ "<violation "
				+ "beginline=\"25\" endline=\"25\" begincolumn=\"4\" endcolumn=\"41\" rule=\"GuardLogStatement\" "
				+ "ruleset=\"Best Practices\" package=\"de.PMD_Report_Extractor.util\" class=\"ResourceFileHandler\" "
				+ "method=\"readFile\" externalInfoUrl=\"https://pmd.github.io/pmd-6.29.0/pmd_rules_java_bestpractices.html"
				+ "#guardlogstatement\" priority=\"2\">\nLogger calls should be surrounded by log level guards.\n"
				+ "</violation>"
				+ "<violation "
				+ "beginline=\"39\" endline=\"39\" begincolumn=\"4\" endcolumn=\"44\" rule=\"GuardLogStatement\" "
				+ "ruleset=\"Best Practices\" package=\"de.PMD_Report_Extractor.util\" class=\"ResourceFileHandler\" "
				+ "method=\"writeToFile\" externalInfoUrl=\"https://pmd.github.io/pmd-6.29.0/pmd_rules_java_bestpractices.html"
				+ "#guardlogstatement\" priority=\"2\">\nLogger calls should be surrounded by log level guards.\n"
				+ "</violation>\r\n"
				+ "</file>\r\n"
				+ "</pmd>";
	}
}
